apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-cert
  namespace: openshift-ingress
spec:
  secretName: apps-wildcard-cert-tls
  commonName: "*.apps.CLUSTERNAME.EXAMPLE.COM"
  dnsNames:
    - "*.apps.CLUSTERNAME.EXAMPLE.COM"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
