apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver-cert
  namespace: openshift-config
spec:
  secretName: apiserver-cert-tls
  commonName: "api.CLUSTERNAME.EXAMPLE.COM"
  dnsNames:
    - "api.CLUSTERNAME.EXAMPLE.COM"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
